### ISSUE TITLE
Minted instructions don't seem to work

### ISSUE THREAD

**Issue by bgavran** [AlxHnr/latex_preview#1]
So I've been using latex_preview for a while and it seems to work nicely!
However, I can't seem to get it to work with minted!
The readme instructions tell me to put the first line of code in the latex source and second in vimrc, but they don't seem to do anything.
```
\usepackage[outputdir=.latex_preview_build_dir]{minted}
let g:latex_preview#compiler_args = '-shell-escape'
```
Compiler args don't really seem to pass the "-shell-escape" to pdflatex. I've circumvented it by changing the engine to "pdflatex -shell-escape", but I still have the problem of latex_preview_build_dir not really pointing anywhere.
As far as I can see, latex_preview stores the temp files in /tmp/random_letters/2/* directory and not in .latex_preview_build_dir?

**Comment by AlxHnr** [comment]
Are you sure you are using the latest commit from master? It shouldn't store anything in `/tmp` anymore and also respect the `g:latex_preview#compiler_args` option.

Im sorry it took me 3 days to answer.

Edit: Do you use any other latex_preview options in your vimrc?

**Comment by bgavran** [comment]
I was afraid I wasn't missing anything obvious - turns out I was!
Yeah, doing a git pull solved the problem completely! I tried so many things to fix it except this :)
Now everything is working as described

Thank you for the help!
